<?php
/**
 * Digit Software Solutions.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category  Dss
 * @package   Dss_CustomerAvatar
 * @author    Extension Team
 * @copyright Copyright (c) 2024 Digit Software Solutions. ( https://digitsoftsol.com )
 */
?>
<?php
$_items = $block->getReviewsCollection()->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($_items)):?>
<div class="block review-list" id="customer-reviews">
    <div class="block-title">
        <strong><?= $escaper->escapeHtml(__('Customers Reviews')) ?></strong>
    </div>
    <div class="block-content">
        <div class="toolbar review-toolbar">
            <?= $block->getChildHtml('toolbar') ?>
        </div>
        <ol class="items review-items">
        <?php foreach ($_items as $_review): ?>
            <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
                <div class="review-image">
                    <img src="<?= $escaper->escapeUrl($block->getLayout()
                        ->createBlock(\Dss\CustomerAvatar\Block\Attributes\Avatar::class)
                        ->getCustomerAvatarById($escaper->escapeHtml($_review->getData('customer_id')))) ?>"
                        width="150px" height="150px" alt="<?= $escaper->escapeHtml('avatar') ?>" />
                </div>
                <div class="review-infor">
                    <div class="review-title" itemprop="name"><?= $escaper->escapeHtml($_review->getTitle()) ?></div>
                    <div class="review-details">
                        <?php if (count($_review->getRatingVotes())): ?>
                            <div class="review-ratings">
                                <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                                <div class="rating-summary item" itemprop="reviewRating"
                                    itemscope itemtype="http://schema.org/Rating">
                                    <span class="label rating-label"><span>
                                        <?= $escaper->escapeHtml($_vote->getRatingCode()) ?></span></span>
                                    <div class="rating-result"
                                        title="<?= $escaper->escapeHtml($_vote->getPercent()) ?>%">
                                        <meta itemprop="worstRating" content="1"/>
                                        <meta itemprop="bestRating" content="100"/>
                                        <span style="width:<?= $escaper->escapeHtml($_vote->getPercent()) ?>%">
                                            <span itemprop="ratingValue">
                                                <?= $escaper->escapeHtml($_vote->getPercent()) ?>%</span>
                                        </span>
                                    </div>
                                </div>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                        <p class="review-author">
                            <span class="review-details-label"><?= $escaper->escapeHtml(__('Review by')) ?></span>
                            <strong class="review-details-value" itemprop="author">
                                <?= $escaper->escapeHtml($_review->getNickname()) ?>
                            </strong>
                        </p>
                        <p class="review-date">
                            <span class="review-details-label"><?= $escaper->escapeHtml(__('Posted on')) ?></span>
                            <time class="review-details-value" itemprop="datePublished" datetime=
                                "<?= $escaper->escapeHtml($block->formatDate($_review->getCreatedAt(), $format)) ?>">
                                    <?= $escaper->escapeHtml($block->formatDate($_review->getCreatedAt(), $format)) ?>
                            </time>
                        </p>
                    </div>
                </div>
                <div class="review-content" itemprop="description">
                    <?= $escaper->escapeHtml(nl2br($escaper->escapeHtml($_review->getDetail()))) ?>
                </div>
            </li>
        <?php endforeach; ?>
        </ol>
        <div class="toolbar review-toolbar">
            <?= $block->getChildHtml('toolbar') ?>
        </div>
    </div>
</div>
<?php endif; ?>
