<?php
/**
 * Digit Software Solutions.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category  Dss
 * @package   Dss_CustomerAvatar
 * @author    Extension Team
 * @copyright Copyright (c) 2024 Digit Software Solutions. ( https://digitsoftsol.com )
 */

/** @var \Magento\Customer\Block\Form\Edit $block */
?>
<form class="form form-edit-account" action="<?= $escaper->escapeHtml($block->getUrl('customer/account/editPost')) ?>"
    method="post" id="form-validate" enctype="multipart/form-data"
    data-hasrequired="<?= $escaper->escapeHtml(__('* Required Fields')) ?>" autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Account Information')) ?></span></legend>
        <br>
        <?= $block->getLayout()->createBlock(Magento\Customer\Block\Widget\Name::class)
            ->setObject($block->getCustomer())->toHtml() ?>
        <div class="field field-name-avatar">
            <?php $avatarFile = !empty($block->getCustomer()->getCustomAttribute('profile_picture'))
                ? $block->getLayout()->createBlock(Dss\CustomerAvatar\Block\Attributes\Avatar::class)
                    ->checkImageFile($block->getCustomer()
                        ->getCustomAttribute('profile_picture')->getValue()) : false; ?>
            <?php $avatar = ($avatarFile)
                ? $block->getUrl(
                    'viewfile/avatar/view/',
                    [
                        'image' => base64_encode(
                            $block->getCustomer()->getCustomAttribute('profile_picture')->getValue()
                        )
                    ]
                )
                : $block->getViewFileUrl('Dss_CustomerAvatar::images/no-profile-photo.jpg'); ?>
            <label class="label" for="profile_picture">
                <span class="avatar-title"><?= $escaper->escapeHtml(__('Profile Picture')); ?></span>
                <img src="<?= $escaper->escapeHtml($avatar); ?>" width="150px" height="150px" alt="profile-picture"
                    title="<?= $escaper->escapeHtml(__('Upload new avatar')); ?>" class="profile-image" />
            </label>
            <div class="control">
                <label for="profile_picture" class="avatar-file-upload">
                    <?= $escaper->escapeHtml(__('Upload new avatar')); ?>
                </label>
                <input type="file" id="profile_picture" name="profile_picture" value="" title="Your avatar"
                    class="avatar validate-image" />
            </div>
        </div>
        <?php $_dob = $block->getLayout()->createBlock(Magento\Customer\Block\Widget\Dob::class) ?>
        <?php $_taxvat = $block->getLayout()->createBlock(Magento\Customer\Block\Widget\Taxvat::class) ?>
        <?php $_gender = $block->getLayout()->createBlock(Magento\Customer\Block\Widget\Gender::class) ?>
        <?php if ($_dob->isEnabled()): ?>
            <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>
        <div class="field choice">
            <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1"
                title="<?= $escaper->escapeHtml(__('Change Email')) ?>" class="checkbox" />
            <label class="label" for="change-email"><span><?= $escaper->escapeHtml(__('Change Email')) ?></span></label>
        </div>
        <div class="field choice">
            <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1"
                title="<?= $escaper->escapeHtml(__('Change Password')) ?>" <?php if ($block->getChangePassword()): ?>
                    checked="checked" <?php endif; ?> class="checkbox" />
            <label class="label"
                for="change-password"><span><?= $escaper->escapeHtml(__('Change Password')) ?></span></label>
        </div>
    </fieldset>

    <fieldset class="fieldset password" data-container="change-email-password">
        <legend class="legend">
            <span data-title="change-email-password">
                <?= $escaper->escapeHtml(__('Change Email and Password')) ?>
            </span>
        </legend><br>
        <div class="field email required" data-container="change-email">
            <label class="label" for="email"><span><?= $escaper->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email" autocomplete="email" data-input="change-email"
                    value="<?= $escaper->escapeHtml($block->getCustomer()->getEmail()) ?>"
                    title="<?= $escaper->escapeHtml(__('Email')) ?>" class="input-text"
                    data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="field password current required">
            <label class="label"
                for="current-password"><span><?= $escaper->escapeHtml(__('Current Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="current_password" id="current-password"
                    data-input="current-password" autocomplete="off" />
            </div>
        </div>
        <div class="field new password required" data-container="new-password"
            data-mage-init='{"passwordStrengthIndicator": {}}'>
            <label class="label" for="password">
                <span><?= $escaper->escapeHtml(__('New Password')) ?>
                </span>
            </label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password"
                    data-password-min-length="<?= $escaper->escapeHtml($block->getMinimumPasswordLength()) ?>"
                    data-password-min-character-sets="
                    <?= $escaper->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>" data-input="new-password"
                    data-validate="{required:true, 'validate-customer-password':true}" autocomplete="off" />
                <div id="password-strength-meter-container" data-role="password-strength-meter">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $escaper->escapeHtml(__('Password Strength')); ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $escaper->escapeHtml(__('No Password')); ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirm password required" data-container="confirm-password">
            <label class="label" for="password-confirmation">
                <span><?= $escaper->escapeHtml(__('Confirm New Password')) ?>
                </span>
            </label>
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                    data-input="confirm-password" autocomplete="off" />
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $escaper->escapeHtml(__('Save')) ?>">
                <span><?= $escaper->escapeHtml(__('Save')) ?>
                </span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $escaper->escapeHtml(__('Go back')) ?>
                </span>
            </a>
        </div>
    </div>
</form>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function ($) {
        var dataForm = $('#form-validate');
        var ignore = <?= /* @escapeNotVerified */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;

        dataForm.mage('validation', {
            <?php if ($_dob->isEnabled()): ?>
                        errorPlacement: function (error, element) {
                    if (element.prop('id').search('full') !== -1) {
                        var dobElement = $(element).parents('.customer-dob'),
                            errorClass = error.prop('class');
                        error.insertAfter(element.parent());
                        dobElement.find('.validate-custom').addClass(errorClass)
                            .after('<div class="' + errorClass + '"></div>');
                    }
                    else {
                        error.insertAfter(element);
                    }
                },
                ignore: ':hidden:not(' + ignore + ')'
        <?php else: ?>
                ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php endif ?>
        });

    });
</script>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $escaper->escapeHtml(__('Change Email')) ?>",
                "titleChangePassword": "<?= $escaper->escapeHtml(__('Change Password')) ?>",
                "titleChangeEmailAndPassword": "<?= $escaper->escapeHtml(__('Change Email and Password')) ?>"
            }
        }
    }
</script>